// src/App.tsx
import Map from './components/Map/Map'
import DateCalculator from './components/DateCalculator/DateCalculator'
import DateReminder from './components/DateReminder/DateReminder'
import ChartComponent from './components/ChartComponent/ChartComponent'
import styles from './App.module.css'

export default function App() {
  return (
    <main>
      <Map />
      <div className={styles.wrap}>
        <DateCalculator />
        <DateReminder />
      </div>
      <div className={styles.chart}>
        <ChartComponent />
      </div>
    </main>
  )
}

// src/App.svelte
<script>
    import DateCalculator from "./DateCalculator.svelte";
    import DateReminder from "./DateReminder.svelte";
    import ChartComponent from './ChartComponent.svelte';
    import Map from "./Map.svelte";
</script>

<main >
    <Map/>
    <div class="wrap">
        <DateCalculator/>
        <DateReminder/>
    </div>
    <div class="chart">
        <ChartComponent/>
    </div>
</main>

<style>
    :global(*) {
        box-sizing: border-box;
    }

    :global(body) {
        background-color: rgb(231, 231, 231);
    }

    .wrap {
        display: flex;
        justify-content: space-around;
        margin: 0 auto;
    }
</style>
